apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: worktrail-updates
  namespace: jobbsporet
  labels:
    team: jobbsporet
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720 #30 days
  acl:
    - team: jobbsporet
      application: sf-pubsub-worktrail-updates
      access: readwrite
    - team: teamoppfolging
      application: teamoppfolging-kafka
      access: read
