metadata:
  namespace: team-jobbsporet
  labels:
    team: team-jobbsporet
spec:
  env:
    - name: WHITELIST_FILE
      value: "/whitelist/user-updates/prod.json"
    - name: KAFKA_TOPIC
      value: "team-jobbsporet.user-updates"
    - name: SALESFORCE_TOPIC
      value: "/event/IPSRoleUserEvent__e"
