apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-pubsub
  namespace: teamcrm
  labels:
    team: teamcrm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  terminationGracePeriodSeconds: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://sf-pubsub.intern.dev.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - azp_name
          - NAVident
    sidecar:
      enabled: false # Currently cannot use - causes 404 when app tries calling dev-fss-pub.nais.io ingresses
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
        - application: itestapp
          namespace: teamcrm
    outbound:
      external:
        - host: api.pubsub.salesforce.com
  kafka:
    pool: nav-dev
  envFrom:
    - secret: sf-pubsub
  env:
    - name: SF_TOKENHOST
      value: https://login.salesforce.com/services/oauth2/token
