apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: bjorn-message
  namespace: teamcrm
  labels:
    team: teamcrm
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720 #30 days
  acl:
    - team: teamcrm
      application: sf-pubsub-bjornmessage
      access: readwrite
    - team: teamcrm
      application: sf-bjorntest
      access: readwrite
    - team: teamcrm
      application: itestapp3
      access: readwrite