apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: task
  namespace: team-dialog
  labels:
    team: team-dialog
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720 #30 days
  acl:
    - team: teamcrm
      application: sf-pubsub-task
      access: readwrite
    - team: teamcrm
      application: sf-bjorntest
      access: readwrite
    - team: teamoppfolging
      application: teamoppfolging-kafka
      access: read
    - team: team-dialog
      application: sf-dvh
      access: read