apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: employer-activity
  namespace: team-dialog
  labels:
    team: team-dialog
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720 #30 days
  acl:
    - team: team-dialog
      application: sf-pubsub-employer-activity
      access: readwrite
    - team: teamoppfolging
      application: teamoppfolging-kafka
      access: read
    - team: team-dialog
      application: sf-dvh
      access: read
    - application: lydia-api
      namespace: pia
      access: read