apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "{{ DEPLOY_APP }}"
  namespace: platforce
  labels:
    team: platforce
spec:
  image: "{{ image }}"
  port: 8080
  secureLogs:
    enabled: true
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  terminationGracePeriodSeconds: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        extra:
          - azp_name
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
        - application: itestapp
          namespace: teamcrm
    outbound:
      external:
        - host: login.salesforce.com
        - host: api.pubsub.salesforce.com
          ports:
            - port: 7443
  kafka:
    pool: nav-prod
  valkey:
    - instance: replay
      access: readwrite
  envFrom:
    - secret: sf-pubsub-prod
  env:
    - name: SF_TOKENHOST
      value: https://login.salesforce.com/services/oauth2/token
    - name: DEPLOY_APP
      value: '{{ DEPLOY_APP }}'
    - name: SALESFORCE_VERSION
      value: 'v65.0'
