name: Preconfigured run on push

on:
  push:
    paths-ignore:
      - .topic/**

jobs:
  build-deploy:
    uses: ./.github/workflows/workflow.yml
    permissions:
      id-token: write
      contents: write
    secrets: inherit
    with:
      DEPLOY_APP: sf-pubsub-bjornmessage     # use ALL to deploy all apps in cluster
      DEPLOY_CLUSTER: dev-gcp
