name: Preconfigured run on push

on:
  push:
    paths-ignore:
      - README.md
      - .topic/**
      - .github/workflows/topics.yml

jobs:
  build-deploy:
    uses: ./.github/workflows/workflow.yml
    permissions:
      id-token: write
      contents: write
    secrets: inherit
    with:
      DEPLOY_APP: sf-pubsub-application-event
      DEPLOY_CLUSTER: dev-gcp
      DEPLOY_NAMESPACE: teamcrm               # TODO replace with folder structure or file scanning in future to support deploy ALL
