name: Preconfigured run on push

on:
  push:
    paths-ignore:
      - README.md
      - .topic/**
      - .github/workflows/topics.yml

jobs:
  build-deploy:
    uses: ./.github/workflows/workflow.yml
    permissions:
      id-token: write
      contents: write
    secrets: inherit
    with:
      DEPLOY_APP: sf-pubsub-employer-activity  # use ALL to deploy all apps in cluster
      DEPLOY_CLUSTER: prod-gcp
      DEPLOY_NAMESPACE: team-dialog                 # TODO replace with folder structure or file scanning in future to support deploy ALL
